### ISSUE TITLE
[Error] req_proxy = RequestProxy() error

### ISSUE THREAD

**Issue by mnlbox** [pgaref/HTTP_Request_Randomizer#29] opened 2017-06-11 05:30 UTC
Hi @pgaref ,
I installed your package with `sudo pip install http-request-randomizer` and want test it with same code as on project README but it's return below error:
```
Traceback (most recent call last):
  File "myTest.py", line 7, in <module>
    req_proxy = RequestProxy()
  File "/usr/local/lib/python2.7/dist-packages/http_request_randomizer/requests/proxy/requestProxy.py", line 55, in __init__
    self.proxy_list += parsers[i].parse_proxyList()
  File "/usr/local/lib/python2.7/dist-packages/http_request_randomizer/requests/parsers/FreeProxyParser.py", line 29, in parse_proxyList
    headings = [th.get_text() for th in table.find("tr").find_all("th")]
AttributeError: 'NoneType' object has no attribute 'find'
```

Can you help me?

**Comment by pgaref** [comment] 2017-06-11 16:54
Hello @mnlbox 

As it turns out free-proxy-list website changed recently causing the parser to fail.
Until I fix the issue you could use the package by checking out the github code and commenting out the specific parser.

Cheers,
Panagiotis

**Comment by pgaref** [comment] 2017-06-11 17:59
@mnlbox 

The issue is now fixed! Please use the latest package version (1.0.5)

Cheers,
Panagiotis

**Closed by pgaref** 2017-06-11 17:59 UTC

**Comment by mnlbox** [comment] 2017-06-24 11:52
Thanks man 😉

**Comment by MASSKAgithub** [comment] 2023-10-23 09:19
same problem now, pls update
